import { Buffer } from "node:buffer";
import { lstat, open, readdir, readFile, writeFile } from "node:fs/promises";
import { basename, dirname, join, relative } from "node:path";
import { transform } from "@reckona/mreact-compiler";

const generatedFileMarker = "// Generated by @reckona/mreact-next. Do not edit.";
const ignoredSourceDirectories = new Set([
  ".cache",
  ".git",
  ".mreact",
  ".next",
  ".vite",
  "build",
  "coverage",
  "dist",
  "node_modules",
  "out",
]);

/** Configures the root directory scanned for `.mreact.tsx` component files. */
export interface GenerateMreactComponentsOptions {
  rootDir: string;
}

/** Describes one source component and the wrapper and DOM modules generated for it. */
export interface GeneratedMreactComponent {
  source: string;
  output: string;
  domOutput: string;
}

/** Contains the generated wrapper module code and browser DOM module code for a component file. */
export interface CompiledMreactComponentModule {
  wrapperCode: string;
  domCode: string;
}

type OutputSnapshot =
  | { kind: "absent" }
  | { code: string; dev: number; ino: number; kind: "file" }
  | { kind: "unsupported" };

interface WrapperComponent {
  exportName: string;
  moduleAccess: string;
  name: string;
}

/** Generates wrapper and DOM modules for every `.mreact.tsx` component under a root directory. */
export async function generateMreactComponents(
  options: GenerateMreactComponentsOptions,
): Promise<GeneratedMreactComponent[]> {
  const sources = await findMreactSources(options.rootDir);
  const pending = await Promise.all(
    sources.map(async (source) => {
      const code = await readFile(source, "utf8");
      const output = outputPathForSource(source);
      const domOutput = domOutputPathForSource(source);
      const generatedCode = compileMreactComponentModule(code, source, {
        domImportPath: importPathForGeneratedModule(output, domOutput),
      });

      return { source, output, domOutput, ...generatedCode };
    }),
  );
  const preflight = await Promise.all(
    pending.map(async (item) => {
      const [outputSnapshot, domOutputSnapshot] = await Promise.all([
        inspectOutput(item.output),
        inspectOutput(item.domOutput),
      ]);
      const legacyPair =
        outputSnapshot.kind === "file" &&
        domOutputSnapshot.kind === "file" &&
        isLegacyGeneratedPair(
          outputSnapshot.code,
          domOutputSnapshot.code,
          importPathForGeneratedModule(item.output, item.domOutput),
        );

      return {
        ...item,
        outputSnapshot,
        domOutputSnapshot,
        collisions: [
          isOutputCollision(outputSnapshot, legacyPair) ? item.output : undefined,
          isOutputCollision(domOutputSnapshot, legacyPair) ? item.domOutput : undefined,
        ],
      };
    }),
  );
  const collisions = preflight
    .flatMap((item) => item.collisions)
    .filter((path): path is string => path !== undefined)
    .sort();

  if (collisions.length > 0) {
    throw new Error(
      `Refusing to overwrite files not generated by @reckona/mreact-next:\n${collisions.map((path) => `- ${path}`).join("\n")}`,
    );
  }

  for (const item of preflight) {
    await writeGeneratedOutput(item.output, item.wrapperCode, item.outputSnapshot);
    await writeGeneratedOutput(item.domOutput, item.domCode, item.domOutputSnapshot);
  }

  return preflight.map(({ source, output, domOutput }) => ({ source, output, domOutput }));
}

/** Configures the import path from the wrapper module to the generated DOM module. */
export interface CompileMreactComponentModuleOptions {
  domImportPath: string;
}

/** Compiles one `.mreact.tsx` component module into wrapper and DOM module source code. */
export function compileMreactComponentModule(
  code: string,
  filename: string,
  options: CompileMreactComponentModuleOptions,
): CompiledMreactComponentModule {
  const compiled = transform({
    code,
    filename,
    target: "client",
    dev: true,
  });

  if (compiled.metadata.components.length === 0) {
    throw new Error(`${filename} must export at least one mreact JSX component.`);
  }

  const components = compiled.metadata.components
    .filter((component) => hasSourceExport(code, component.name, component.exportName))
    .map((component) => ({
      name: component.name,
      exportName: component.exportName,
      moduleAccess:
        component.exportName === "default" ? "module.default" : `module.${component.name}`,
    }));

  if (components.length === 0) {
    throw new Error(`${filename} must export at least one mreact JSX component.`);
  }
  return {
    wrapperCode: renderWrapperModule(components, options.domImportPath, true),
    domCode: `${generatedFileMarker}
// @ts-nocheck
${compiled.code}`,
  };
}

function renderWrapperModule(
  components: readonly WrapperComponent[],
  domImportPath: string,
  includeMarker: boolean,
): string {
  const wrappers = components
    .map(
      (component) => `const ${component.name}$mounted = new WeakMap<Element, Node>();
const ${component.name}$mounting = new WeakSet<Element>();
${emitExportFunction(component.exportName, component.name)}(props: Record<string, unknown>): never {
  return (
    <span
      data-mreact-component=${JSON.stringify(component.name)}
      ref={(node: Element | null) => {
      if (node === null || ${component.name}$mounted.has(node) || ${component.name}$mounting.has(node)) {
        return;
      }

      ${component.name}$mounting.add(node);
      void import(${JSON.stringify(domImportPath)}).then((module) => {
        const rendered = (${component.moduleAccess} as (props: Record<string, unknown>) => Node)(props);
        node.replaceChildren(rendered);
        ${component.name}$mounted.set(node, rendered);
      });
      }}
    />
  ) as never;
}`,
    )
    .join("\n\n");

  return `${includeMarker ? `${generatedFileMarker}\n` : ""}// @ts-nocheck
"use client";
${wrappers}
`;
}

async function findMreactSources(rootDir: string): Promise<string[]> {
  const entries = await readdir(rootDir, { withFileTypes: true });
  const sources: string[] = [];

  for (const entry of entries) {
    const path = join(rootDir, entry.name);

    if (entry.isDirectory() && !ignoredSourceDirectories.has(entry.name)) {
      sources.push(...(await findMreactSources(path)));
      continue;
    }

    if (entry.isFile() && entry.name.endsWith(".mreact.tsx")) {
      sources.push(path);
    }
  }

  return sources.sort();
}

async function inspectOutput(path: string): Promise<OutputSnapshot> {
  let pathStats;
  try {
    pathStats = await lstat(path);
  } catch (error) {
    if (isErrorWithCode(error, "ENOENT")) {
      return { kind: "absent" };
    }
    throw error;
  }

  if (!pathStats.isFile() || pathStats.nlink !== 1) {
    return { kind: "unsupported" };
  }

  const handle = await open(path, "r");
  try {
    const openedStats = await handle.stat();
    if (
      !openedStats.isFile() ||
      openedStats.nlink !== 1 ||
      openedStats.dev !== pathStats.dev ||
      openedStats.ino !== pathStats.ino
    ) {
      return { kind: "unsupported" };
    }

    return {
      code: await handle.readFile({ encoding: "utf8" }),
      dev: openedStats.dev,
      ino: openedStats.ino,
      kind: "file",
    };
  } finally {
    await handle.close();
  }
}

function isOwnedGeneratedFile(code: string): boolean {
  return code.split(/\r?\n/u, 1)[0] === generatedFileMarker;
}

function isLegacyGeneratedPair(
  wrapperCode: string,
  domCode: string,
  domImportPath: string,
): boolean {
  const normalizedWrapper = normalizeLineEndings(wrapperCode);
  const componentNames = normalizedWrapper.split("\n").flatMap((line) => {
    const match = /^const (.+)\$mounted = new WeakMap<Element, Node>\(\);$/u.exec(line);
    return match?.[1] === undefined ? [] : [match[1]];
  });
  const components = componentNames.map((name): WrapperComponent => {
    const isDefault = normalizedWrapper.includes(`export default function ${name}(`);
    return {
      exportName: isDefault ? "default" : name,
      moduleAccess: isDefault ? "module.default" : `module.${name}`,
      name,
    };
  });

  return (
    components.length > 0 &&
    new Set(componentNames).size === componentNames.length &&
    normalizedWrapper ===
      normalizeLineEndings(renderWrapperModule(components, domImportPath, false)) &&
    isLegacyGeneratedDomModule(domCode)
  );
}

function isLegacyGeneratedDomModule(code: string): boolean {
  const normalized = normalizeLineEndings(code);
  return (
    normalized.startsWith("// @ts-nocheck\n") &&
    normalized.includes('from "@reckona/mreact-reactive-dom";')
  );
}

function isOutputCollision(snapshot: OutputSnapshot, legacyPair: boolean): boolean {
  return (
    snapshot.kind === "unsupported" ||
    (snapshot.kind === "file" && !isOwnedGeneratedFile(snapshot.code) && !legacyPair)
  );
}

async function writeGeneratedOutput(
  path: string,
  code: string,
  snapshot: OutputSnapshot,
): Promise<void> {
  if (snapshot.kind === "absent") {
    await writeFile(path, code, { encoding: "utf8", flag: "wx" });
    return;
  }
  if (snapshot.kind !== "file") {
    throw new Error(`Generated output is no longer safe to write: ${path}`);
  }

  const pathStats = await lstat(path);
  if (
    !pathStats.isFile() ||
    pathStats.nlink !== 1 ||
    pathStats.dev !== snapshot.dev ||
    pathStats.ino !== snapshot.ino
  ) {
    throw new Error(`Generated output changed after preflight: ${path}`);
  }

  const handle = await open(path, "r+");
  try {
    const openedStats = await handle.stat();
    const currentCode = await handle.readFile({ encoding: "utf8" });
    if (
      !openedStats.isFile() ||
      openedStats.nlink !== 1 ||
      openedStats.dev !== snapshot.dev ||
      openedStats.ino !== snapshot.ino ||
      currentCode !== snapshot.code
    ) {
      throw new Error(`Generated output changed after preflight: ${path}`);
    }

    const bytes = Buffer.from(code);
    await handle.truncate(0);
    let offset = 0;
    while (offset < bytes.length) {
      const { bytesWritten } = await handle.write(bytes, offset, bytes.length - offset, offset);
      if (bytesWritten === 0) {
        throw new Error(`Generated output could not be written completely: ${path}`);
      }
      offset += bytesWritten;
    }
    await handle.truncate(bytes.length);
  } finally {
    await handle.close();
  }
}

function normalizeLineEndings(code: string): string {
  return code.replaceAll("\r\n", "\n");
}

function isErrorWithCode(error: unknown, code: string): boolean {
  return (
    error !== null &&
    typeof error === "object" &&
    "code" in error &&
    (error as { code: unknown }).code === code
  );
}

function outputPathForSource(source: string): string {
  return join(dirname(source), `${basename(source, ".mreact.tsx")}.tsx`);
}

function domOutputPathForSource(source: string): string {
  return join(dirname(source), `${basename(source, ".mreact.tsx")}.mreact-dom.ts`);
}

function importPathForGeneratedModule(from: string, to: string): string {
  const extensionless = relative(dirname(from), to).replace(/\.ts$/, "");

  return extensionless.startsWith(".") ? extensionless : `./${extensionless}`;
}

function emitExportFunction(exportName: string, name: string): string {
  return exportName === "default" ? `export default function ${name}` : `export function ${name}`;
}

function hasSourceExport(code: string, name: string, exportName: string): boolean {
  if (exportName === "default") {
    return /\bexport\s+default\b/.test(code);
  }

  return (
    new RegExp(`\\bexport\\s+(?:async\\s+)?function\\s+${escapeRegExp(name)}\\b`).test(code) ||
    new RegExp(`\\bexport\\s+(?:const|let|var)\\s+${escapeRegExp(name)}\\b`).test(code) ||
    new RegExp(`\\bexport\\s*\\{[^}]*\\b${escapeRegExp(exportName)}\\b[^}]*\\}`).test(code)
  );
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Formats generated component paths as a human-readable CLI summary. */
export function formatGeneratedMreactComponents(
  generated: readonly GeneratedMreactComponent[],
  rootDir: string,
): string {
  if (generated.length === 0) {
    return "No .mreact.tsx components found.";
  }

  return generated
    .map(
      (item) =>
        `${relative(rootDir, item.source)} -> ${relative(rootDir, item.output)}, ${relative(rootDir, item.domOutput)}`,
    )
    .join("\n");
}
