import { createStrykerConfig } from "./stryker.base.config.mjs";

export default createStrykerConfig({
  name: "compiler",
  breakThreshold: 80,
  mutate: [
    "packages/compiler/src/emit-client.ts:773-775",
    "packages/compiler/src/emit-client.ts:777-777",
    "packages/compiler/src/emit-client.ts:810-810",
    "packages/compiler/src/emit-client.ts:822-822",
    "packages/compiler/src/emit-client.ts:1198-1201",
    "packages/compiler/src/emit-server.ts:2719-2721",
    "packages/compiler/src/emit-server-stream.ts:4098-4100",
    "packages/compiler/src/oxc-child-analysis.ts:647-647",
    "packages/compiler/src/oxc-child-analysis.ts:695-695",
    "packages/compiler/src/oxc-render-values.ts:86-90",
    "packages/compiler/src/oxc-render-values.ts:174-174",
    "packages/compiler/src/oxc-render-values.ts:191-191",
    "packages/compiler/src/oxc-render-values.ts:204-210",
    "packages/compiler/src/oxc-render-values.ts:228-233",
    "packages/compiler/src/oxc-render-values.ts:319-325",
    "packages/compiler/src/oxc-render-values.ts:376-377",
    "packages/compiler/src/oxc-render-values.ts:382-387",
    "packages/compiler/src/oxc-render-values.ts:399-399",
    "packages/compiler/src/oxc-render-values.ts:404-410",
    "packages/compiler/src/oxc-render-values.ts:423-423",
    "packages/compiler/src/oxc-render-values.ts:425-427",
    "packages/compiler/src/oxc-render-values.ts:446-446",
    "packages/compiler/src/oxc-render-values.ts:456-456",
    "packages/compiler/src/oxc-render-values.ts:479-483",
    "packages/compiler/src/oxc-render-values.ts:488-489",
    "packages/compiler/src/oxc-render-values.ts:492-493",
    "packages/compiler/src/oxc-render-values.ts:500-502",
    "packages/compiler/src/oxc.ts:1862-1867",
    "packages/compiler/src/oxc.ts:2054-2056",
  ],
  testFiles: ["packages/compiler/test/**/*.test.ts"],
});
