import { createStrykerConfig } from "./stryker.base.config.mjs";

export default createStrykerConfig({
  name: "reactive-core",
  breakThreshold: 80,
  mutate: [
    "packages/reactive-core/src/effect.ts:21-25",
    "packages/reactive-core/src/effect.ts:70-95",
    "packages/reactive-core/src/effect.ts:115-135",
    "packages/reactive-core/src/effect.ts:146-192",
    "packages/reactive-core/src/effect.ts:194-215",
    "packages/reactive-core/src/computed.ts:26-32",
    "packages/reactive-core/src/computed.ts:67-68",
    "packages/reactive-core/src/computed.ts:149-152",
    "packages/reactive-core/src/computed.ts:391-392",
    "packages/reactive-core/src/computed.ts:98-112",
    "packages/reactive-core/src/computed.ts:300-300",
    "packages/reactive-core/src/computed.ts:348-348",
    "packages/reactive-core/src/computed.ts:132-138",
    "packages/reactive-core/src/computed.ts:193-275",
    "packages/reactive-core/src/computed.ts:338-346",
    "packages/reactive-core/src/computed.ts:449-494",
    "packages/reactive-core/src/computed.ts:497-535",
    "packages/reactive-core/src/tracking.ts:253-311",
    "packages/reactive-core/src/tracking.ts:313-331",
    "packages/reactive-core/src/tracking.ts:332-483",
    "packages/reactive-core/src/scheduler.ts:71-84",
    "packages/reactive-core/src/cleanup-scope.ts:102-105",
    "packages/reactive-core/src/cleanup-scope.ts:119-133",
    "packages/reactive-core/src/state.ts:98-111",
    "packages/reactive-core/src/state.ts:123-159",
    "packages/reactive-core/src/cell.ts:102-145",
  ],
  testFiles: [
    "packages/reactive-core/test/effect-wakeup.test.ts",
    "packages/reactive-core/test/effect.test.ts",
    "packages/reactive-core/test/effect-manual-dispose.test.ts",
    "packages/reactive-core/test/effect-cleanup-reentry.test.ts",
    "packages/reactive-core/test/effect-dispose-during-run.test.ts",
    "packages/reactive-core/test/dormant-dependency-snapshot.test.ts",
    "packages/reactive-core/test/computed-notification-completeness.test.ts",
    "packages/reactive-core/test/computed-notification-generative.test.ts",
    "packages/reactive-core/test/pending-computed-wide-graph.test.ts",
    "packages/reactive-core/test/pending-computed-recovery.test.ts",
    "packages/reactive-core/test/pending-computed-merge-order.test.ts",
    "packages/reactive-core/test/scheduler-and-tracking.test.ts",
    "packages/reactive-core/test/cleanup-scope.test.ts",
    "packages/reactive-core/test/error.test.ts",
    "packages/reactive-core/test/coverage-fill.test.ts",
    "packages/reactive-core/test/more-edges.test.ts",
    "packages/reactive-core/test/dormant-validation.test.ts",
    "packages/reactive-core/test/source-version.test.ts",
    "packages/reactive-core/test/tracking-performance.test.ts",
    "packages/reactive-core/test/computed.test.ts",
    "packages/reactive-core/test/deferred-computed.test.ts",
    "packages/reactive-core/test/deferred-dormant-diamond.test.ts",
    "packages/reactive-core/test/cell.test.ts",
    "packages/reactive-core/test/batch.test.ts",
    "packages/reactive-core/test/batch-computed-reads.test.ts",
    "packages/reactive-core/test/devtools.test.ts",
    "packages/reactive-core/test/selector.test.ts",
  ],
});
