import { createStrykerConfig } from "./stryker.base.config.mjs";

export default createStrykerConfig({
  name: "reactive-core",
  breakThreshold: 80,
  mutate: [
    "packages/reactive-core/src/effect.ts:21-25",
    "packages/reactive-core/src/effect.ts:70-95",
    "packages/reactive-core/src/effect.ts:115-135",
    "packages/reactive-core/src/effect.ts:146-192",
    "packages/reactive-core/src/effect.ts:194-215",
    "packages/reactive-core/src/computed.ts:158-208",
    "packages/reactive-core/src/computed.ts:365-420",
    "packages/reactive-core/src/computed.ts:422-460",
    "packages/reactive-core/src/tracking.ts:253-309",
    "packages/reactive-core/src/tracking.ts:311-385",
    "packages/reactive-core/src/cleanup-scope.ts:102-105",
    "packages/reactive-core/src/cleanup-scope.ts:119-133",
    "packages/reactive-core/src/state.ts:87-100",
    "packages/reactive-core/src/state.ts:112-148",
    "packages/reactive-core/src/cell.ts:102-145",
  ],
  testFiles: [
    "packages/reactive-core/test/effect.test.ts",
    "packages/reactive-core/test/effect-manual-dispose.test.ts",
    "packages/reactive-core/test/effect-cleanup-reentry.test.ts",
    "packages/reactive-core/test/effect-dispose-during-run.test.ts",
    "packages/reactive-core/test/dormant-dependency-snapshot.test.ts",
    "packages/reactive-core/test/computed-notification-completeness.test.ts",
    "packages/reactive-core/test/computed-notification-generative.test.ts",
    "packages/reactive-core/test/scheduler-and-tracking.test.ts",
    "packages/reactive-core/test/cleanup-scope.test.ts",
    "packages/reactive-core/test/error.test.ts",
    "packages/reactive-core/test/coverage-fill.test.ts",
    "packages/reactive-core/test/more-edges.test.ts",
    "packages/reactive-core/test/dormant-validation.test.ts",
    "packages/reactive-core/test/source-version.test.ts",
    "packages/reactive-core/test/tracking-performance.test.ts",
    "packages/reactive-core/test/computed.test.ts",
    "packages/reactive-core/test/deferred-computed.test.ts",
    "packages/reactive-core/test/cell.test.ts",
    "packages/reactive-core/test/batch.test.ts",
    "packages/reactive-core/test/devtools.test.ts",
    "packages/reactive-core/test/selector.test.ts",
  ],
});
