export interface SyntheticEvent {
  bubbles: boolean;
  cancelable: boolean;
  defaultPrevented: boolean;
  eventPhase: number;
  isTrusted: boolean;
  nativeEvent: Event;
  timeStamp: number;
  type: string;
  target: EventTarget | null;
  currentTarget: EventTarget | null;
  pointerId?: number;
  pointerType?: string;
  isPrimary?: boolean;
  clientX?: number;
  clientY?: number;
  pageX?: number;
  pageY?: number;
  screenX?: number;
  screenY?: number;
  button?: number;
  buttons?: number;
  ctrlKey?: boolean;
  shiftKey?: boolean;
  altKey?: boolean;
  metaKey?: boolean;
  relatedTarget?: EventTarget | null;
  touches?: TouchList;
  changedTouches?: TouchList;
  key?: string;
  persist(): void;
  preventDefault(): void;
  stopPropagation(): void;
  isDefaultPrevented(): boolean;
  isPersistent(): boolean;
  isPropagationStopped(): boolean;
}
