import {
  Component,
  PureComponent,
} from "./class-component.js";
import {
  Fragment,
  Activity,
  Profiler,
  Suspense,
  SuspenseList,
  StrictMode,
  Children,
  cloneElement,
  createElement,
  createErrorBoundary,
  createPortal,
  createRef,
  forwardRef,
  isValidElement,
  lazy,
  memo,
} from "./element.js";
import {
  createContext,
  renderContextConsumerToString,
  renderContextProviderToString,
  useContext,
} from "./context.js";
import {
  applyStreamingHydrationFragments,
  createRoot,
  createStreamingHydrationRoot,
  enableEventHydrationManifestReplay,
  enableHydrationEventReplay,
  flushSync,
  hydrateRoot,
  queueHydrationEvent,
  readEventHydrationManifest,
  render,
  unmountComponentAtNode,
} from "./render.js";
import {
  useCallback,
  useDebugValue,
  useDeferredValue,
  useEffectEvent,
  useEffect,
  useId,
  useImperativeHandle,
  useInsertionEffect,
  useLayoutEffect,
  useMemo,
  useOptimistic,
  useReducer,
  useRef,
  useState,
  useSyncExternalStore,
  use,
  useActionState,
  act,
  cache,
  cacheSignal,
  captureOwnerStack,
  startTransition,
  unstable_useCacheRefresh,
  useTransition,
  version,
} from "./hooks.js";
import { renderToString } from "./server-render.js";

const ReactCompat = {
  Component,
  PureComponent,
  Fragment,
  Activity,
  Profiler,
  Suspense,
  SuspenseList,
  StrictMode,
  Children,
  cloneElement,
  createElement,
  createErrorBoundary,
  createPortal,
  createRef,
  forwardRef,
  isValidElement,
  lazy,
  memo,
  createContext,
  renderContextConsumerToString,
  renderContextProviderToString,
  useContext,
  applyStreamingHydrationFragments,
  createRoot,
  createStreamingHydrationRoot,
  enableEventHydrationManifestReplay,
  enableHydrationEventReplay,
  flushSync,
  hydrateRoot,
  queueHydrationEvent,
  readEventHydrationManifest,
  render,
  unmountComponentAtNode,
  useCallback,
  useDebugValue,
  useDeferredValue,
  useEffectEvent,
  useEffect,
  useId,
  useImperativeHandle,
  useInsertionEffect,
  useLayoutEffect,
  useMemo,
  useOptimistic,
  useReducer,
  useRef,
  useState,
  useSyncExternalStore,
  use,
  useActionState,
  act,
  cache,
  cacheSignal,
  captureOwnerStack,
  renderToString,
  startTransition,
  unstable_useCacheRefresh,
  useTransition,
  version,
} as const;

export default ReactCompat;
