import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, test, vi } from "vitest";
import type { AppRouterCache } from "../src/cache.js";
import { renderAppRequest } from "../src/render.js";

describe("mreact app server actions", () => {
  test("renders form action metadata for imported use-server actions", async () => {
    const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-render-"));
    await writeActionFixture(appDir);

    const response = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/"),
    });
    const html = await response.text();

    expect(response.headers.get("set-cookie")).toContain("mreact.csrf=");
    expect(html).toContain('method="post"');
    expect(html).toContain('action="/_mreact/actions"');
    expect(html).toContain('name="__mreact_module_id" value="actions.ts"');
    expect(html).toContain('name="__mreact_export_name" value="save"');
    expect(html).toContain('name="__mreact_csrf"');
    expect(html).toContain('name="__mreact_action_nonce"');
  });

  test("recognizes use-server directives after leading comments", async () => {
    const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-comment-directive-"));
    await writeActionFixture(appDir, "./actions", "// generated by a fixture\n");

    const response = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/"),
    });
    const html = await response.text();

    expect(html).toContain('action="/_mreact/actions"');
    expect(html).toContain('name="__mreact_module_id" value="actions.ts"');
    expect(html).toContain('name="__mreact_export_name" value="save"');
  });

  test("resolves TypeScript server actions imported with the TS-ESM .js suffix", async () => {
    const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-js-suffix-"));
    await writeActionFixture(appDir, "./actions.js");

    const response = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/"),
    });
    const html = await response.text();

    expect(response.status).toBe(200);
    expect(html).toContain('action="/_mreact/actions"');
    expect(html).toContain('name="__mreact_module_id" value="actions.ts"');
    expect(html).toContain('name="__mreact_export_name" value="save"');
  });

  test("dispatches form posts to registered use-server actions", async () => {
    const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-post-"));
    await writeActionFixture(appDir);

    const pageResponse = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/"),
    });
    const html = await pageResponse.text();
    const csrf = extractInputValue(html, "__mreact_csrf");
    const nonce = extractInputValue(html, "__mreact_action_nonce");
    const cookie = pageResponse.headers.get("set-cookie")?.split(";")[0] ?? "";
    const body = new URLSearchParams({
      __mreact_action_nonce: nonce,
      __mreact_csrf: csrf,
      __mreact_export_name: "save",
      __mreact_module_id: "actions.ts",
      title: "Ship app router",
    });

    const response = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/_mreact/actions", {
        body,
        headers: {
          "content-type": "application/x-www-form-urlencoded",
          cookie,
        },
        method: "POST",
      }),
    });

    expect(response.status).toBe(200);
    await expect(response.json()).resolves.toEqual({
      ok: true,
      value: { title: "Ship app router" },
    });
    expect((globalThis as { __mreactActionCalls?: unknown[] }).__mreactActionCalls).toEqual([
      "Ship app router",
    ]);
  });

  test("rejects server action requests over the configured content length limit", async () => {
    const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-body-limit-"));
    await writeActionFixture(appDir);
    delete (globalThis as { __mreactActionCalls?: unknown[] }).__mreactActionCalls;
    const response = await renderAppRequest({
      appDir,
      serverActions: { maxBodyBytes: 16 },
      request: new Request("http://local.test/_mreact/actions", {
        body: new URLSearchParams({
          __mreact_action_nonce: "nonce-large",
          __mreact_csrf: "csrf-large",
          __mreact_export_name: "save",
          __mreact_module_id: "actions.ts",
          title: "Large",
        }),
        headers: {
          "content-length": "17",
          "content-type": "application/x-www-form-urlencoded",
          cookie: "mreact.csrf=csrf-large",
        },
        method: "POST",
      }),
    });

    expect(response.status).toBe(413);
    await expect(response.json()).resolves.toEqual({
      ok: false,
      error: "Server action request body is too large.",
    });
    expect((globalThis as { __mreactActionCalls?: unknown[] }).__mreactActionCalls).toBeUndefined();
  });

  test("dispatches JSON server action requests through the hardened transport", async () => {
    const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-json-"));
    await writeActionFixture(appDir);
    const response = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/_mreact/actions", {
        body: JSON.stringify({
          args: ["JSON title"],
          exportName: "echo",
          moduleId: "actions.ts",
        }),
        headers: {
          "content-type": "application/json",
          cookie: "mreact.csrf=csrf-json",
          "x-mreact-action-nonce": "nonce-json",
          "x-mreact-csrf": "csrf-json",
        },
        method: "POST",
      }),
    });

    expect(response.status).toBe(200);
    await expect(response.json()).resolves.toEqual({
      ok: true,
      value: { title: "JSON title" },
    });
  });

  test("rejects registered JSON actions outside the configured allowlist", async () => {
    const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-allowlist-json-"));
    await writeActionFixture(appDir);
    const response = await renderAppRequest({
      appDir,
      serverActions: {
        allowedActions: [{ moduleId: "actions.ts", exportName: "save" }],
      },
      request: new Request("http://local.test/_mreact/actions", {
        body: JSON.stringify({
          args: ["Blocked"],
          exportName: "echo",
          moduleId: "actions.ts",
        }),
        headers: {
          "content-type": "application/json",
          cookie: "mreact.csrf=csrf-allowlist-json",
          "x-mreact-action-nonce": "nonce-allowlist-json",
          "x-mreact-csrf": "csrf-allowlist-json",
        },
        method: "POST",
      }),
    });

    expect(response.status).toBe(404);
    await expect(response.json()).resolves.toEqual({
      ok: false,
      error: "Unknown server action.",
    });
  });

  test("rejects registered form actions outside the configured allowlist", async () => {
    const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-allowlist-form-"));
    await writeActionFixture(appDir);
    const pageResponse = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/"),
    });
    const html = await pageResponse.text();
    const csrf = extractInputValue(html, "__mreact_csrf");
    const nonce = extractInputValue(html, "__mreact_action_nonce");
    const cookie = pageResponse.headers.get("set-cookie")?.split(";")[0] ?? "";
    const response = await renderAppRequest({
      appDir,
      serverActions: {
        allowedActions: [{ moduleId: "actions.ts", exportName: "save" }],
      },
      request: new Request("http://local.test/_mreact/actions", {
        body: new URLSearchParams({
          __mreact_action_nonce: nonce,
          __mreact_csrf: csrf,
          __mreact_export_name: "echo",
          __mreact_module_id: "actions.ts",
          title: "Blocked",
        }),
        headers: {
          "content-type": "application/x-www-form-urlencoded",
          cookie,
        },
        method: "POST",
      }),
    });

    expect(response.status).toBe(404);
    await expect(response.json()).resolves.toEqual({
      ok: false,
      error: "Unknown server action.",
    });
  });

  test("authorizes JSON server action requests before invoking actions", async () => {
    const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-json-authorize-"));
    await writeActionFixture(appDir);
    const seen: unknown[] = [];
    const response = await renderAppRequest({
      appDir,
      serverActions: {
        authorize(_request, reference, args) {
          seen.push({ args, reference });
          return reference.exportName === "echo" ? "Denied by app policy." : true;
        },
      },
      request: new Request("http://local.test/_mreact/actions", {
        body: JSON.stringify({
          args: ["JSON title"],
          exportName: "echo",
          moduleId: "actions.ts",
        }),
        headers: {
          "content-type": "application/json",
          cookie: "mreact.csrf=csrf-json-authorize",
          "x-mreact-action-nonce": "nonce-json-authorize",
          "x-mreact-csrf": "csrf-json-authorize",
        },
        method: "POST",
      }),
    });

    expect(response.status).toBe(403);
    await expect(response.json()).resolves.toEqual({
      ok: false,
      error: "Denied by app policy.",
    });
    expect(seen).toEqual([
      {
        args: ["JSON title"],
        reference: { exportName: "echo", moduleId: "actions.ts" },
      },
    ]);
  });

  test("authorizes form server action requests before invoking actions", async () => {
    const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-form-authorize-"));
    await writeActionFixture(appDir);
    const pageResponse = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/"),
    });
    const html = await pageResponse.text();
    const csrf = extractInputValue(html, "__mreact_csrf");
    const nonce = extractInputValue(html, "__mreact_action_nonce");
    const cookie = pageResponse.headers.get("set-cookie")?.split(";")[0] ?? "";
    const seen: unknown[] = [];
    const response = await renderAppRequest({
      appDir,
      serverActions: {
        authorize(_request, reference, args) {
          const formData = args[0] as FormData;
          seen.push({
            reference,
            title: formData.get("title"),
          });
          return false;
        },
      },
      request: new Request("http://local.test/_mreact/actions", {
        body: new URLSearchParams({
          __mreact_action_nonce: nonce,
          __mreact_csrf: csrf,
          __mreact_export_name: "save",
          __mreact_module_id: "actions.ts",
          title: "Blocked",
        }),
        headers: {
          "content-type": "application/x-www-form-urlencoded",
          cookie,
        },
        method: "POST",
      }),
    });

    expect(response.status).toBe(403);
    await expect(response.json()).resolves.toEqual({
      ok: false,
      error: "Server action not authorized.",
    });
    expect(seen).toEqual([
      {
        reference: { exportName: "save", moduleId: "actions.ts" },
        title: "Blocked",
      },
    ]);
    expect((globalThis as { __mreactActionCalls?: unknown[] }).__mreactActionCalls).not.toEqual([
      "Blocked",
    ]);
  });

  test("rejects JSON server action requests without a matching CSRF token", async () => {
    const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-json-csrf-"));
    await writeActionFixture(appDir);
    const response = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/_mreact/actions", {
        body: JSON.stringify({
          args: ["JSON title"],
          exportName: "echo",
          moduleId: "actions.ts",
        }),
        headers: {
          "content-type": "application/json",
          cookie: "mreact.csrf=csrf-json",
          "x-mreact-action-nonce": "nonce-json-csrf",
          "x-mreact-csrf": "wrong",
        },
        method: "POST",
      }),
    });

    expect(response.status).toBe(403);
    await expect(response.json()).resolves.toEqual({
      ok: false,
      error: "Invalid CSRF token.",
    });
  });

  test("rejects form server action requests without a matching CSRF token before invocation", async () => {
    const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-form-csrf-"));
    await writeActionFixture(appDir);
    const pageResponse = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/"),
    });
    const html = await pageResponse.text();
    const nonce = extractInputValue(html, "__mreact_action_nonce");
    const cookie = pageResponse.headers.get("set-cookie")?.split(";")[0] ?? "";
    const response = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/_mreact/actions", {
        body: new URLSearchParams({
          __mreact_action_nonce: nonce,
          __mreact_csrf: "wrong",
          __mreact_export_name: "save",
          __mreact_module_id: "actions.ts",
          title: "Blocked CSRF",
        }),
        headers: {
          "content-type": "application/x-www-form-urlencoded",
          cookie,
        },
        method: "POST",
      }),
    });

    expect(response.status).toBe(403);
    await expect(response.json()).resolves.toEqual({
      ok: false,
      error: "Invalid CSRF token.",
    });
    expect((globalThis as { __mreactActionCalls?: unknown[] }).__mreactActionCalls).not.toEqual([
      "Blocked CSRF",
    ]);
  });

  test("rejects production server action requests without Origin or Referer", async () => {
    await withNodeEnv("production", async () => {
      const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-origin-missing-"));
      await writeActionFixture(appDir);
      const pageResponse = await renderAppRequest({
        appDir,
        request: new Request("https://local.test/"),
      });
      const html = await pageResponse.text();
      const csrf = extractInputValue(html, "__mreact_csrf");
      const nonce = extractInputValue(html, "__mreact_action_nonce");
      const cookie = pageResponse.headers.get("set-cookie")?.split(";")[0] ?? "";
      const response = await renderAppRequest({
        appDir,
        request: new Request("https://local.test/_mreact/actions", {
          body: new URLSearchParams({
            __mreact_action_nonce: nonce,
            __mreact_csrf: csrf,
            __mreact_export_name: "save",
            __mreact_module_id: "actions.ts",
            title: "Blocked origin",
          }),
          headers: {
            "content-type": "application/x-www-form-urlencoded",
            cookie,
          },
          method: "POST",
        }),
      });

      expect(response.status).toBe(403);
      await expect(response.json()).resolves.toEqual({
        ok: false,
        error: "Origin not allowed.",
      });
    });
  });

  test("accepts production server action requests with a same-origin Referer", async () => {
    await withNodeEnv("production", async () => {
      const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-referer-"));
      await writeActionFixture(appDir);
      const warn = vi.spyOn(console, "warn").mockImplementation(() => {});
      const pageResponse = await renderAppRequest({
        appDir,
        request: new Request("https://local.test/"),
      });
      const html = await pageResponse.text();
      const csrf = extractInputValue(html, "__mreact_csrf");
      const nonce = extractInputValue(html, "__mreact_action_nonce");
      const cookie = pageResponse.headers.get("set-cookie")?.split(";")[0] ?? "";
      const response = await renderAppRequest({
        appDir,
        request: new Request("https://local.test/_mreact/actions", {
          body: new URLSearchParams({
            __mreact_action_nonce: nonce,
            __mreact_csrf: csrf,
            __mreact_export_name: "save",
            __mreact_module_id: "actions.ts",
            title: "Allowed referer",
          }),
          headers: {
            "content-type": "application/x-www-form-urlencoded",
            cookie,
            referer: "https://local.test/form",
          },
          method: "POST",
        }),
      });

      expect(response.status).toBe(200);
      expect(warn).toHaveBeenCalledWith(expect.stringContaining("allowedActions"));
      warn.mockRestore();
    });
  });

  test("rejects unsupported server action content types without throwing", async () => {
    const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-content-type-"));
    await writeActionFixture(appDir);
    const response = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/_mreact/actions", {
        body: "not a form body",
        headers: {
          "content-type": "text/plain",
        },
        method: "POST",
      }),
    });

    expect(response.status).toBe(415);
    await expect(response.json()).resolves.toEqual({
      ok: false,
      error: "Unsupported server action content type.",
    });
  });

  test("rejects server action package imports unless explicitly allowed", async () => {
    const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-package-policy-"));
    await writePackageFixture(appDir);
    await writeFile(
      join(appDir, "actions.ts"),
      `"use server";
import { version } from "fixture-lib";

export function echo() {
  return { version };
}`,
    );

    const blocked = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/_mreact/actions", {
        body: JSON.stringify({
          args: [],
          exportName: "echo",
          moduleId: "actions.ts",
        }),
        headers: {
          "content-type": "application/json",
          cookie: "mreact.csrf=csrf-package-policy",
          "x-mreact-action-nonce": "nonce-package-policy",
          "x-mreact-csrf": "csrf-package-policy",
        },
        method: "POST",
      }),
    });
    const allowed = await renderAppRequest({
      appDir,
      importPolicy: { allowedPackages: ["fixture-lib"] },
      request: new Request("http://local.test/_mreact/actions", {
        body: JSON.stringify({
          args: [],
          exportName: "echo",
          moduleId: "actions.ts",
        }),
        headers: {
          "content-type": "application/json",
          cookie: "mreact.csrf=csrf-package-allowed",
          "x-mreact-action-nonce": "nonce-package-allowed",
          "x-mreact-csrf": "csrf-package-allowed",
        },
        method: "POST",
      }),
    });

    expect(blocked.status).toBe(500);
    await expect(blocked.json()).resolves.toEqual({
      ok: false,
      error: expect.stringContaining('"fixture-lib" is imported by a server action'),
    });
    expect(allowed.status).toBe(200);
    await expect(allowed.json()).resolves.toMatchObject({
      ok: true,
      value: { version: "fixture-ok" },
    });
  });

  test("rejects JSON server action nonce replay", async () => {
    const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-json-replay-"));
    await writeActionFixture(appDir);
    const request = () =>
      renderAppRequest({
        appDir,
        request: new Request("http://local.test/_mreact/actions", {
          body: JSON.stringify({
            args: ["JSON title"],
            exportName: "echo",
            moduleId: "actions.ts",
          }),
          headers: {
            "content-type": "application/json",
            cookie: "mreact.csrf=csrf-json",
            "x-mreact-action-nonce": "nonce-json-replay",
            "x-mreact-csrf": "csrf-json",
          },
          method: "POST",
        }),
      });

    expect((await request()).status).toBe(200);
    const replay = await request();

    expect(replay.status).toBe(409);
    await expect(replay.json()).resolves.toEqual({
      ok: false,
      error: "Server action nonce was already used.",
    });
  });

  test("uses an injected replay store for JSON server action nonce checks", async () => {
    const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-json-store-"));
    await writeActionFixture(appDir);
    const replayStore = createRecordingReplayStore();
    const response = await renderAppRequest({
      appDir,
      serverActions: { replayStore },
      request: new Request("http://local.test/_mreact/actions", {
        body: JSON.stringify({
          args: ["JSON title"],
          exportName: "echo",
          moduleId: "actions.ts",
        }),
        headers: {
          "content-type": "application/json",
          cookie: "mreact.csrf=csrf-json-store",
          "x-mreact-action-nonce": "nonce-json-store",
          "x-mreact-csrf": "csrf-json-store",
        },
        method: "POST",
      }),
    });

    expect(response.status).toBe(200);
    expect(replayStore.calls).toEqual(["has:nonce-json-store", "add:nonce-json-store"]);
  });

  test("rejects form action replay nonce reuse", async () => {
    const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-replay-"));
    await writeActionFixture(appDir);
    const pageResponse = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/"),
    });
    const html = await pageResponse.text();
    const csrf = extractInputValue(html, "__mreact_csrf");
    const nonce = extractInputValue(html, "__mreact_action_nonce");
    const cookie = pageResponse.headers.get("set-cookie")?.split(";")[0] ?? "";

    const submit = () =>
      renderAppRequest({
        appDir,
        request: new Request("http://local.test/_mreact/actions", {
          body: new URLSearchParams({
            __mreact_action_nonce: nonce,
            __mreact_csrf: csrf,
            __mreact_export_name: "save",
            __mreact_module_id: "actions.ts",
            title: "Replay",
          }),
          headers: {
            "content-type": "application/x-www-form-urlencoded",
            cookie,
          },
          method: "POST",
        }),
      });

    expect((await submit()).status).toBe(200);
    const replay = await submit();

    expect(replay.status).toBe(409);
    await expect(replay.json()).resolves.toEqual({
      ok: false,
      error: "Server action nonce was already used.",
    });
  });

  test("uses an injected replay store for form server action nonce checks", async () => {
    const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-form-store-"));
    await writeActionFixture(appDir);
    const replayStore = createRecordingReplayStore();
    const pageResponse = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/"),
    });
    const html = await pageResponse.text();
    const csrf = extractInputValue(html, "__mreact_csrf");
    const nonce = extractInputValue(html, "__mreact_action_nonce");
    const cookie = pageResponse.headers.get("set-cookie")?.split(";")[0] ?? "";
    const response = await renderAppRequest({
      appDir,
      serverActions: { replayStore },
      request: new Request("http://local.test/_mreact/actions", {
        body: new URLSearchParams({
          __mreact_action_nonce: nonce,
          __mreact_csrf: csrf,
          __mreact_export_name: "save",
          __mreact_module_id: "actions.ts",
          title: "Store",
        }),
        headers: {
          "content-type": "application/x-www-form-urlencoded",
          cookie,
        },
        method: "POST",
      }),
    });

    expect(response.status).toBe(200);
    expect(replayStore.calls).toEqual([`has:${nonce}`, `add:${nonce}`]);
  });

  test("returns form action redirect responses without JSON wrapping", async () => {
    const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-form-redirect-"));
    await writeActionFixture(appDir);
    const pageResponse = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/"),
    });
    const html = await pageResponse.text();
    const csrf = extractInputValue(html, "__mreact_csrf");
    const nonce = extractInputValue(html, "__mreact_action_nonce");
    const cookie = pageResponse.headers.get("set-cookie")?.split(";")[0] ?? "";
    const response = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/_mreact/actions", {
        body: new URLSearchParams({
          __mreact_action_nonce: nonce,
          __mreact_csrf: csrf,
          __mreact_export_name: "redirectToThanks",
          __mreact_module_id: "actions.ts",
        }),
        headers: {
          "content-type": "application/x-www-form-urlencoded",
          cookie,
        },
        method: "POST",
      }),
    });

    expect(response.status).toBe(303);
    expect(response.headers.get("location")).toBe("/thanks");
    expect(response.headers.get("content-type")).toBeNull();
    await expect(response.text()).resolves.toBe("");
  });

  test("redirects form actions with void-like returns back to the same-origin referer", async () => {
    const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-form-void-"));
    await writeActionFixture(appDir);
    const pageResponse = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/"),
    });
    const html = await pageResponse.text();
    const csrf = extractInputValue(html, "__mreact_csrf");
    const nonce = extractInputValue(html, "__mreact_action_nonce");
    const cookie = pageResponse.headers.get("set-cookie")?.split(";")[0] ?? "";

    for (const exportName of ["saveVoid", "saveNull", "saveUndefined"]) {
      const response = await renderAppRequest({
        appDir,
        request: new Request("http://local.test/_mreact/actions", {
          body: new URLSearchParams({
            __mreact_action_nonce: `${nonce}-${exportName}`,
            __mreact_csrf: csrf,
            __mreact_export_name: exportName,
            __mreact_module_id: "actions.ts",
            title: exportName,
          }),
          headers: {
            "content-type": "application/x-www-form-urlencoded",
            cookie,
            referer: "http://local.test/server-actions?tab=notes",
          },
          method: "POST",
        }),
      });

      expect(response.status).toBe(303);
      expect(response.headers.get("location")).toBe("/server-actions?tab=notes");
      expect(response.headers.get("content-type")).toBeNull();
      await expect(response.text()).resolves.toBe("");
    }
  });

  test("does not redirect void form actions to a cross-origin referer", async () => {
    const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-form-void-origin-"));
    await writeActionFixture(appDir);
    const pageResponse = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/"),
    });
    const html = await pageResponse.text();
    const csrf = extractInputValue(html, "__mreact_csrf");
    const nonce = extractInputValue(html, "__mreact_action_nonce");
    const cookie = pageResponse.headers.get("set-cookie")?.split(";")[0] ?? "";
    const response = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/_mreact/actions", {
        body: new URLSearchParams({
          __mreact_action_nonce: nonce,
          __mreact_csrf: csrf,
          __mreact_export_name: "saveVoid",
          __mreact_module_id: "actions.ts",
          title: "bad referer",
        }),
        headers: {
          "content-type": "application/x-www-form-urlencoded",
          cookie,
          referer: "https://evil.test/phish",
        },
        method: "POST",
      }),
    });

    expect(response.status).toBe(303);
    expect(response.headers.get("location")).toBe("/");
  });

  test("returns form action navigation HTML responses without JSON wrapping", async () => {
    const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-form-navigation-"));
    await writeActionFixture(appDir);
    const pageResponse = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/"),
    });
    const html = await pageResponse.text();
    const csrf = extractInputValue(html, "__mreact_csrf");
    const nonce = extractInputValue(html, "__mreact_action_nonce");
    const cookie = pageResponse.headers.get("set-cookie")?.split(";")[0] ?? "";
    const response = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/_mreact/actions", {
        body: new URLSearchParams({
          __mreact_action_nonce: nonce,
          __mreact_csrf: csrf,
          __mreact_export_name: "renderSavedPage",
          __mreact_module_id: "actions.ts",
        }),
        headers: {
          "content-type": "application/x-www-form-urlencoded",
          cookie,
        },
        method: "POST",
      }),
    });

    expect(response.status).toBe(200);
    expect(response.headers.get("content-type")).toBe("text/html; charset=utf-8");
    await expect(response.text()).resolves.toBe("<!DOCTYPE html><main>Saved</main>");
  });

  test("server actions can revalidate cached routes", async () => {
    const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-revalidate-"));
    await mkdir(appDir, { recursive: true });
    await writeFile(
      join(appDir, "actions.ts"),
      `"use server";

import { revalidatePath } from "@reckona/mreact-router";

export function invalidateHome() {
  revalidatePath("/");
  return "ok";
}`,
    );
    await writeFile(
      join(appDir, "page.mreact.tsx"),
      `export const revalidate = 60;

export function loader() {
  const state = globalThis as { __mreactActionRevalidateCalls?: number };
  state.__mreactActionRevalidateCalls = (state.__mreactActionRevalidateCalls ?? 0) + 1;
  return { calls: state.__mreactActionRevalidateCalls };
}

export default function Page(props) {
  return <main>calls: {props.data.calls}</main>;
}`,
    );

    const first = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/"),
    });
    const cached = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/"),
    });
    const action = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/_mreact/actions", {
        body: JSON.stringify({
          args: [],
          exportName: "invalidateHome",
          moduleId: "actions.ts",
        }),
        headers: {
          "content-type": "application/json",
          cookie: "mreact.csrf=csrf-revalidate",
          "x-mreact-action-nonce": "nonce-revalidate",
          "x-mreact-csrf": "csrf-revalidate",
        },
        method: "POST",
      }),
    });
    const afterRevalidate = await renderAppRequest({
      appDir,
      request: new Request("http://local.test/"),
    });

    expect(await first.text()).toContain("<main>calls: 1</main>");
    expect(await cached.text()).toContain("<main>calls: 1</main>");
    expect(action.status).toBe(200);
    expect(await afterRevalidate.text()).toContain("<main>calls: 2</main>");
  });

  test("server action revalidation uses the injected route cache adapter", async () => {
    const appDir = await mkdtemp(join(tmpdir(), "mreact-app-actions-cache-adapter-"));
    const routeCache = createRecordingRouteCache();
    await mkdir(appDir, { recursive: true });
    await writeFile(
      join(appDir, "actions.ts"),
      `"use server";

import { revalidatePath } from "@reckona/mreact-router";

export function invalidateHome() {
  revalidatePath("/");
  return "ok";
}`,
    );

    const response = await renderAppRequest({
      appDir,
      routeCache,
      request: new Request("http://local.test/_mreact/actions", {
        body: JSON.stringify({
          args: [],
          exportName: "invalidateHome",
          moduleId: "actions.ts",
        }),
        headers: {
          "content-type": "application/json",
          cookie: "mreact.csrf=csrf-cache-adapter",
          "x-mreact-action-nonce": "nonce-cache-adapter",
          "x-mreact-csrf": "csrf-cache-adapter",
        },
        method: "POST",
      }),
    });

    expect(response.status).toBe(200);
    expect(response.headers.get("x-mreact-revalidate")).toBe("/");
    expect(routeCache.calls).toContain("deleteByPath:/");
  });
});

function createRecordingReplayStore(): {
  add(value: string): void;
  calls: string[];
  has(value: string): boolean;
} {
  const seen = new Set<string>();
  const calls: string[] = [];

  return {
    calls,
    add(value) {
      calls.push(`add:${value}`);
      seen.add(value);
    },
    has(value) {
      calls.push(`has:${value}`);
      return seen.has(value);
    },
  };
}

async function writeActionFixture(
  appDir: string,
  actionSource = "./actions",
  actionPrefix = "",
): Promise<void> {
  await mkdir(appDir, { recursive: true });
  await writeFile(
    join(appDir, "actions.ts"),
    `${actionPrefix}"use server";

export async function save(formData: FormData) {
  const title = String(formData.get("title"));
  (globalThis as { __mreactActionCalls?: unknown[] }).__mreactActionCalls = [title];
  return { title };
}

export function echo(title: string) {
  return { title };
}

export function redirectToThanks() {
  return new Response(null, {
    headers: { location: "/thanks" },
    status: 303,
  });
}

export function renderSavedPage() {
  return new Response("<!DOCTYPE html><main>Saved</main>", {
    headers: { "content-type": "text/html; charset=utf-8" },
    status: 200,
  });
}

export async function saveVoid(formData: FormData): Promise<void> {
  const title = String(formData.get("title"));
  (globalThis as { __mreactActionCalls?: unknown[] }).__mreactActionCalls = [title];
}

export function saveNull() {
  return null;
}

export function saveUndefined() {
  return undefined;
}`,
  );
  await writeFile(
    join(appDir, "page.mreact.tsx"),
    `import { save } from "${actionSource}";

export default function Page() {
  return <main><form action={save}><input name="title" value="Draft" /><button type="submit">Save</button></form></main>;
}`,
  );
}

async function writePackageFixture(appDir: string): Promise<void> {
  const packageDir = join(appDir, "node_modules", "fixture-lib");

  await mkdir(packageDir, { recursive: true });
  await writeFile(
    join(packageDir, "package.json"),
    JSON.stringify({ type: "module", exports: "./index.js" }),
  );
  await writeFile(join(packageDir, "index.js"), 'export const version = "fixture-ok";');
}

function extractInputValue(html: string, name: string): string {
  const match = new RegExp(`name="${name}" value="([^"]+)"`).exec(html);

  if (match?.[1] === undefined) {
    throw new Error(`Input ${name} was not found.`);
  }

  return match[1];
}

function createRecordingRouteCache(): AppRouterCache & { calls: string[] } {
  const calls: string[] = [];

  return {
    calls,
    async deleteByPath(path) {
      calls.push(`deleteByPath:${path}`);
    },
    async get(key) {
      calls.push(`get:${key}`);
      return undefined;
    },
    async set(key, entry) {
      calls.push(`set:${key}:${entry.path}`);
    },
  };
}

async function withNodeEnv<T>(value: string, run: () => Promise<T>): Promise<T> {
  const previous = process.env.NODE_ENV;
  process.env.NODE_ENV = value;

  try {
    return await run();
  } finally {
    if (previous === undefined) {
      delete process.env.NODE_ENV;
    } else {
      process.env.NODE_ENV = previous;
    }
  }
}
