[graph]
targets = [
  "aarch64-apple-darwin",
  "x86_64-pc-windows-msvc",
  "x86_64-unknown-linux-gnu",
]
all-features = true

[advisories]
unmaintained = "workspace"
ignore = []

[bans]
multiple-versions = "warn"
wildcards = "deny"
allow = []
deny = []
skip = []
skip-tree = []

[licenses]
confidence-threshold = 0.93
allow = [
  "Apache-2.0",
  "ISC",
  "MIT",
  "Unicode-3.0",
  "Unlicense",
]
exceptions = [
  { allow = ["NCSA"], name = "libfuzzer-sys" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
