import { link, mkdir, mkdtemp, readFile, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, test } from "vitest";
import {
  compileMreactComponentModule,
  formatGeneratedMreactComponents,
  generateMreactComponents,
  type GeneratedMreactComponent,
} from "../src/index.js";

describe("@reckona/mreact-next additional coverage", () => {
  const component = (name: string, text = name) =>
    `export function ${name}() {\n  return <span>${text}</span>;\n}\n`;

  test("walks nested directories to find .mreact.tsx sources", async () => {
    const rootDir = await mkdtemp(join(tmpdir(), "mreact-next-nested-"));
    const nested = join(rootDir, "components", "deep");
    await mkdir(nested, { recursive: true });

    const ignored = join(rootDir, "components", "notes.txt");
    await writeFile(ignored, "ignored file");

    const sourceTop = join(rootDir, "Top.mreact.tsx");
    const sourceDeep = join(nested, "Deep.mreact.tsx");
    await writeFile(sourceTop, component("Top"));
    await writeFile(sourceDeep, component("Deep"));

    const generated = await generateMreactComponents({ rootDir });

    expect(generated.map((entry) => entry.source).sort()).toEqual([sourceDeep, sourceTop].sort());

    for (const entry of generated) {
      const code = await readFile(entry.output, "utf8");
      expect(code).toContain('"use client";');
    }
  });

  test("refuses hand-written target collisions before writing any generated file", async () => {
    const rootDir = await mkdtemp(join(tmpdir(), "mreact-next-collision-"));
    const safeSource = join(rootDir, "A-Safe.mreact.tsx");
    const domCollisionSource = join(rootDir, "B-DomCollision.mreact.tsx");
    const wrapperCollisionSource = join(rootDir, "C-WrapperCollision.mreact.tsx");
    const domCollision = join(rootDir, "B-DomCollision.mreact-dom.ts");
    const wrapperCollision = join(rootDir, "C-WrapperCollision.tsx");
    const handWrittenDom = "export const handWrittenDom = true;\n";
    const handWrittenWrapper = "export const handWrittenWrapper = true;\n";
    await writeFile(safeSource, component("Safe"));
    await writeFile(domCollisionSource, component("DomCollision"));
    await writeFile(wrapperCollisionSource, component("WrapperCollision"));
    await writeFile(domCollision, handWrittenDom);
    await writeFile(wrapperCollision, handWrittenWrapper);

    let error: unknown;
    try {
      await generateMreactComponents({ rootDir });
    } catch (caught) {
      error = caught;
    }

    expect(error).toBeInstanceOf(Error);
    expect((error as Error).message).toContain(domCollision);
    expect((error as Error).message).toContain(wrapperCollision);
    expect(await readFile(domCollision, "utf8")).toBe(handWrittenDom);
    expect(await readFile(wrapperCollision, "utf8")).toBe(handWrittenWrapper);
    await expect(readFile(join(rootDir, "A-Safe.tsx"), "utf8")).rejects.toMatchObject({
      code: "ENOENT",
    });
    await expect(readFile(join(rootDir, "A-Safe.mreact-dom.ts"), "utf8")).rejects.toMatchObject({
      code: "ENOENT",
    });
    await expect(readFile(join(rootDir, "B-DomCollision.tsx"), "utf8")).rejects.toMatchObject({
      code: "ENOENT",
    });
    await expect(
      readFile(join(rootDir, "C-WrapperCollision.mreact-dom.ts"), "utf8"),
    ).rejects.toMatchObject({ code: "ENOENT" });
  });

  test("updates generator-owned outputs on rerun", async () => {
    const rootDir = await mkdtemp(join(tmpdir(), "mreact-next-rerun-"));
    const source = join(rootDir, "Counter.mreact.tsx");
    const output = join(rootDir, "Counter.tsx");
    const domOutput = join(rootDir, "Counter.mreact-dom.ts");
    await writeFile(source, component("Counter", "Initial"));

    await generateMreactComponents({ rootDir });
    await writeFile(source, component("Counter", "Updated"));
    await generateMreactComponents({ rootDir });

    expect(await readFile(output, "utf8")).toContain(
      "// Generated by @reckona/mreact-next. Do not edit.",
    );
    const domCode = await readFile(domOutput, "utf8");
    expect(domCode).toContain("// Generated by @reckona/mreact-next. Do not edit.");
    expect(domCode).toContain("Updated");
  });

  test("updates generator-owned outputs with CRLF ownership markers", async () => {
    const rootDir = await mkdtemp(join(tmpdir(), "mreact-next-crlf-rerun-"));
    const source = join(rootDir, "Counter.mreact.tsx");
    const output = join(rootDir, "Counter.tsx");
    const domOutput = join(rootDir, "Counter.mreact-dom.ts");
    await writeFile(source, component("Counter", "Initial"));
    await generateMreactComponents({ rootDir });
    await writeFile(output, (await readFile(output, "utf8")).replaceAll("\n", "\r\n"));
    await writeFile(domOutput, (await readFile(domOutput, "utf8")).replaceAll("\n", "\r\n"));
    await writeFile(source, component("Counter", "Updated"));

    await expect(generateMreactComponents({ rootDir })).resolves.toEqual([
      { source, output, domOutput },
    ]);
    expect(await readFile(domOutput, "utf8")).toContain("Updated");
  });

  test("rejects output symlinks without following them outside the root", async () => {
    const rootDir = await mkdtemp(join(tmpdir(), "mreact-next-output-symlink-root-"));
    const outsideDir = await mkdtemp(join(tmpdir(), "mreact-next-output-symlink-outside-"));
    const ownedSource = join(rootDir, "Owned.mreact.tsx");
    const danglingSource = join(rootDir, "Dangling.mreact.tsx");
    const ownedOutput = join(rootDir, "Owned.tsx");
    const danglingOutput = join(rootDir, "Dangling.tsx");
    const outsideOwned = join(outsideDir, "outside-owned.tsx");
    const outsideDangling = join(outsideDir, "outside-dangling.tsx");
    const outsideContents = `// Generated by @reckona/mreact-next. Do not edit.\nOUTSIDE_SENTINEL\n`;
    await writeFile(ownedSource, component("Owned"));
    await writeFile(danglingSource, component("Dangling"));
    await writeFile(outsideOwned, outsideContents);
    await symlink(outsideOwned, ownedOutput, "file");
    await symlink(outsideDangling, danglingOutput, "file");

    await expect(generateMreactComponents({ rootDir })).rejects.toThrow(ownedOutput);

    expect(await readFile(outsideOwned, "utf8")).toBe(outsideContents);
    await expect(readFile(outsideDangling, "utf8")).rejects.toMatchObject({ code: "ENOENT" });
  });

  test("rejects multiply linked output files without modifying the other link", async () => {
    const rootDir = await mkdtemp(join(tmpdir(), "mreact-next-output-hardlink-root-"));
    const outsideDir = await mkdtemp(join(tmpdir(), "mreact-next-output-hardlink-outside-"));
    const source = join(rootDir, "Linked.mreact.tsx");
    const output = join(rootDir, "Linked.tsx");
    const outsideOutput = join(outsideDir, "outside-linked.tsx");
    const outsideContents = `// Generated by @reckona/mreact-next. Do not edit.\nOUTSIDE_HARDLINK_SENTINEL\n`;
    await writeFile(source, component("Linked"));
    await writeFile(outsideOutput, outsideContents);
    await link(outsideOutput, output);

    await expect(generateMreactComponents({ rootDir })).rejects.toThrow(output);
    expect(await readFile(outsideOutput, "utf8")).toBe(outsideContents);
  });

  test("does not claim hand-written files that only resemble legacy output", async () => {
    const rootDir = await mkdtemp(join(tmpdir(), "mreact-next-false-legacy-"));
    const source = join(rootDir, "Panel.mreact.tsx");
    const output = join(rootDir, "Panel.tsx");
    const domOutput = join(rootDir, "Panel.mreact-dom.ts");
    const wrapperCode = `// @ts-nocheck
"use client";
export function Panel() {
  const marker = "data-mreact-component=";
  void import("./Panel.mreact-dom");
  return <article>{marker}</article>;
}
`;
    const domCode = `// @ts-nocheck
import { createTemplate } from "@reckona/mreact-reactive-dom";
export const handWrittenDom = createTemplate("<article>Hand written</article>");
`;
    await writeFile(source, component("Panel", "Generated"));
    await writeFile(output, wrapperCode);
    await writeFile(domOutput, domCode);

    await expect(generateMreactComponents({ rootDir })).rejects.toThrow(output);
    expect(await readFile(output, "utf8")).toBe(wrapperCode);
    expect(await readFile(domOutput, "utf8")).toBe(domCode);
  });

  test("migrates paired legacy generator outputs to ownership markers", async () => {
    const rootDir = await mkdtemp(join(tmpdir(), "mreact-next-legacy-rerun-"));
    const source = join(rootDir, "Legacy.mreact.tsx");
    const output = join(rootDir, "Legacy.tsx");
    const domOutput = join(rootDir, "Legacy.mreact-dom.ts");
    const code = component("Legacy");
    await writeFile(source, code);
    const compiled = compileMreactComponentModule(code, source, {
      domImportPath: "./Legacy.mreact-dom",
    });
    const withoutMarker = (generatedCode: string) =>
      generatedCode.replace("// Generated by @reckona/mreact-next. Do not edit.\n", "");
    await writeFile(output, withoutMarker(compiled.wrapperCode));
    await writeFile(domOutput, withoutMarker(compiled.domCode));
    await writeFile(source, component("Legacy", "Updated after legacy generation"));

    await expect(generateMreactComponents({ rootDir })).resolves.toEqual([
      { source, output, domOutput },
    ]);
    expect(await readFile(output, "utf8")).toContain(
      "// Generated by @reckona/mreact-next. Do not edit.",
    );
    expect(await readFile(domOutput, "utf8")).toContain(
      "// Generated by @reckona/mreact-next. Do not edit.",
    );
    expect(await readFile(domOutput, "utf8")).toContain("Updated after legacy generation");
  });

  test("does not traverse dependency, metadata, or build output directories", async () => {
    const rootDir = await mkdtemp(join(tmpdir(), "mreact-next-ignored-dirs-"));
    const source = join(rootDir, "Visible.mreact.tsx");
    const ignoredDirectories = [
      "node_modules",
      ".git",
      ".mreact",
      ".next",
      ".vite",
      ".cache",
      "coverage",
      "dist",
      "build",
      "out",
    ];
    await writeFile(source, component("Visible"));

    for (const directory of ignoredDirectories) {
      const ignoredDir = join(rootDir, directory, "nested");
      await mkdir(ignoredDir, { recursive: true });
      await writeFile(
        join(ignoredDir, `${directory.replace(/\W/gu, "Ignored")}.mreact.tsx`),
        component("Ignored"),
      );
    }

    const generated = await generateMreactComponents({ rootDir });

    expect(generated).toEqual([
      {
        source,
        output: join(rootDir, "Visible.tsx"),
        domOutput: join(rootDir, "Visible.mreact-dom.ts"),
      },
    ]);
  });

  test("formatGeneratedMreactComponents returns an explanatory message when no components were generated", () => {
    const rootDir = "/tmp/whatever";
    const output = formatGeneratedMreactComponents([], rootDir);
    expect(output).toBe("No .mreact.tsx components found.");
  });

  test("formatGeneratedMreactComponents formats each generated entry relative to the root", () => {
    const rootDir = "/projects/app";
    const generated: GeneratedMreactComponent[] = [
      {
        source: "/projects/app/components/Counter.mreact.tsx",
        output: "/projects/app/components/Counter.tsx",
        domOutput: "/projects/app/components/Counter.mreact-dom.ts",
      },
      {
        source: "/projects/app/page.mreact.tsx",
        output: "/projects/app/page.tsx",
        domOutput: "/projects/app/page.mreact-dom.ts",
      },
    ];

    const formatted = formatGeneratedMreactComponents(generated, rootDir);
    expect(formatted.split("\n")).toEqual([
      "components/Counter.mreact.tsx -> components/Counter.tsx, components/Counter.mreact-dom.ts",
      "page.mreact.tsx -> page.tsx, page.mreact-dom.ts",
    ]);
  });

  test("compileMreactComponentModule throws when source has no exported mreact JSX components", () => {
    const code = `function Counter() {\n  return <span>nope</span>;\n}\n`;
    expect(() =>
      compileMreactComponentModule(code, "Empty.mreact.tsx", { domImportPath: "./dom" }),
    ).toThrow(/must export at least one mreact JSX component/);
  });

  test("compileMreactComponentModule throws when no compiled export matches the metadata", () => {
    const code = `// the compiler will treat this as an exported JSX component\nexport function NeverEmitted() {\n  // intentionally not JSX so the compiler may strip it post-metadata\n  return null;\n}\n`;
    // The simplest reliable way to exercise the secondary throw is via a source
    // whose metadata claims an export that the compiler then renames/strips.
    // We assert that compileMreactComponentModule rejects sources without
    // emitted exports.
    try {
      compileMreactComponentModule(code, "Stripped.mreact.tsx", { domImportPath: "./dom" });
    } catch (error) {
      expect((error as Error).message).toMatch(/must export at least one mreact JSX component/);
      return;
    }
    // If the compiler actually emits, this test does not need to throw.
  });
});
