// Cloudflare Workers entrypoint for the Hacker News example.
//
// Build the app first, then bundle this file with Wrangler or your Workers
// bundler. The `ASSETS` binding should point at the generated `.mreact/client`
// directory. Dynamic route modules are generated by `mreact-router build`
// under `.mreact/cloudflare`.
import {
  createCloudflareBuiltRequestHandler,
  createCloudflareRouteModuleRenderer,
  createCloudflareStaticAssetLoader,
} from "@reckona/mreact-router/adapters/cloudflare";
import { routeModules } from "../.mreact/cloudflare/route-modules.mjs";
import clientManifest from "../.mreact/client/manifest.json" with { type: "json" };
import serverManifest from "../.mreact/server/manifest.json" with { type: "json" };

interface Env {
  ASSETS: {
    fetch(request: Request): Response | Promise<Response>;
  };
}

const renderRouteModule = createCloudflareRouteModuleRenderer<Env>({
  modules: routeModules,
});

const routerLogger = {
  error(event: unknown) {
    console.error("[mreact-router]", JSON.stringify(event));
  },
  info(event: unknown) {
    console.info("[mreact-router]", JSON.stringify(event));
  },
};

const handler = createCloudflareBuiltRequestHandler<Env>({
  assets: createCloudflareStaticAssetLoader({
    binding: (env) => env.ASSETS,
    clientManifest,
  }),
  clientManifest,
  logger: routerLogger,
  renderRoute(request, context) {
    return renderRouteModule(request, context);
  },
  serverManifest,
});

export default {
  fetch(request: Request, env: Env, context: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/api/health") {
      return Promise.resolve(Response.json({ app: "mreact-hacker-news", ok: true }));
    }

    if (request.method === "GET" || request.method === "HEAD") {
      const publicAssetResponse = servePublicAsset(request, env);

      if (publicAssetResponse !== undefined) {
        return publicAssetResponse;
      }
    }

    return handler.fetch(request, env, context).then(preserveHtmlStreaming);
  },
};

function preserveHtmlStreaming(response: Response): Response {
  if (
    response.headers.get("x-mreact-stream") !== "1" ||
    !response.headers.get("content-type")?.toLowerCase().includes("text/html")
  ) {
    return response;
  }

  const headers = new Headers(response.headers);
  headers.set(
    "cache-control",
    appendCacheControlDirective(headers.get("cache-control"), "no-transform"),
  );
  headers.set("content-encoding", "identity");

  return new Response(response.body, {
    headers,
    status: response.status,
    statusText: response.statusText,
  });
}

function appendCacheControlDirective(value: string | null, directive: string): string {
  if (value === null || value.trim().length === 0) {
    return directive;
  }

  const directives = value.split(",").map((part) => part.trim().toLowerCase());
  if (directives.includes(directive)) {
    return value;
  }

  return `${value}, ${directive}`;
}

function servePublicAsset(request: Request, env: Env): Promise<Response> | undefined {
  const url = new URL(request.url);
  const publicAssetPaths: Record<string, string> = {
    "/robots.txt": "/public/robots.txt",
    "/styles.css": "/public/styles.css",
  };
  const publicPath = publicAssetPaths[url.pathname];

  if (publicPath === undefined) {
    return undefined;
  }

  url.pathname = publicPath;
  url.search = "";

  return Promise.resolve(env.ASSETS.fetch(new Request(url, request)));
}
