// Cloudflare Workers entrypoint for the Hacker News example.
//
// Build the app first, then bundle this file with Wrangler or your Workers
// bundler. The `ASSETS` binding should point at the generated `.mreact/client`
// directory. Dynamic route modules are generated by `mreact-router build`
// under `.mreact/cloudflare`.
import {
  createCloudflareBuiltRequestHandler,
  createCloudflareRouteModuleRenderer,
  createCloudflareStaticAssetLoader,
} from "@reckona/mreact-router/adapters/cloudflare";
import { routeModules } from "../.mreact/cloudflare/route-modules.mjs";
import clientManifest from "../.mreact/client/manifest.json" with { type: "json" };
import serverManifest from "../.mreact/server/manifest.json" with { type: "json" };

interface Env {
  ASSETS: {
    fetch(request: Request): Response | Promise<Response>;
  };
}

const renderRouteModule = createCloudflareRouteModuleRenderer<Env>({
  modules: routeModules,
});

const routerLogger = {
  error(event: unknown) {
    console.error("[mreact-router]", JSON.stringify(event));
  },
  info(event: unknown) {
    console.info("[mreact-router]", JSON.stringify(event));
  },
};

const handler = createCloudflareBuiltRequestHandler<Env>({
  assets: createCloudflareStaticAssetLoader({
    binding: (env) => env.ASSETS,
    clientManifest,
  }),
  clientManifest,
  logger: routerLogger,
  renderRoute(request, context) {
    return renderRouteModule(request, context);
  },
  serverManifest,
});

export default {
  fetch(request: Request, env: Env, context: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/api/health") {
      return Promise.resolve(Response.json({ app: "mreact-hacker-news", ok: true }));
    }

    if (request.method === "GET" || request.method === "HEAD") {
      const publicAssetResponse = servePublicAsset(request, env);

      if (publicAssetResponse !== undefined) {
        return publicAssetResponse;
      }
    }

    return handler.fetch(request, env, context);
  },
};

function servePublicAsset(request: Request, env: Env): Promise<Response> | undefined {
  const url = new URL(request.url);

  if (url.pathname !== "/styles.css") {
    return undefined;
  }

  url.pathname = "/public/styles.css";
  url.search = "";

  return Promise.resolve(env.ASSETS.fetch(new Request(url, request)));
}
