export {
  collectClientRouteReferences,
  compilerModuleContextForSource,
  createClientRouteInferenceCache,
  detectAnchorElementUsage,
  detectClientNavigationHint,
  detectClientNavigationOverride,
  detectNavigationRuntimeOverride,
  formatClientRouteInferenceDiagnostic,
  inferClientRouteModule,
  isClientRouteModule,
  isClientRouteSource,
  navigationRuntimeLinkDisabledDiagnostic,
  resolveNavigationRuntime,
  routeToClientManifestEntry,
  type ClientReferenceImport,
  type ClientRouteComponent,
  type ClientRouteComponentClassification,
  type ClientRouteComponentOrigin,
  type ClientRouteInferenceCache,
  type ClientRouteInferenceDiagnostic,
  type ClientRouteInferenceResult,
  type ClientRouteManifestEntry,
  type ClientRouteReferenceResult,
} from "./client.js";
