// Cloudflare Workers entrypoint shape for a built mreact app.
//
// Build the app first, then bundle this file with Wrangler or your
// Workers bundler. The `ASSETS` binding should point at the generated
// `.mreact/client` directory. Dynamic route modules are generated by
// `mreact-router build` under `.mreact/cloudflare`.
import {
  type CloudflareBuiltRouteRenderContext,
  createCloudflareBuiltRequestHandler,
  createCloudflarePrerenderStore,
  createCloudflareRouteModuleRenderer,
  createCloudflareStaticAssetLoader,
} from "@reckona/mreact-router/adapters/cloudflare";
import { routeModules } from "../.mreact/cloudflare/route-modules.mjs";
import clientManifest from "../.mreact/client/manifest.json" with { type: "json" };
import serverManifest from "../.mreact/server/manifest.json" with { type: "json" };

interface Env {
  ASSETS: {
    fetch(request: Request): Response | Promise<Response>;
  };
}

const renderRouteModule = createCloudflareRouteModuleRenderer<Env>({
  modules: routeModules,
});

const handler = createCloudflareBuiltRequestHandler<Env>({
  assets: createCloudflareStaticAssetLoader({
    binding: (env) => env.ASSETS,
    clientManifest,
  }),
  clientManifest,
  renderRoute(request, context) {
    const cache = (globalThis as typeof globalThis & { caches?: { default: Cache } }).caches
      ?.default;

    return renderCloudflareAppRequest(request, context, {
      prerenderStore: cache === undefined ? undefined : createCloudflarePrerenderStore({ cache }),
    });
  },
  serverManifest,
});

export default {
  fetch(request: Request, env: Env, context: ExecutionContext): Promise<Response> {
    return handler.fetch(request, env, context);
  },
};

async function renderCloudflareAppRequest(
  request: Request,
  context: CloudflareBuiltRouteRenderContext<Env>,
  options: {
    prerenderStore?: ReturnType<typeof createCloudflarePrerenderStore> | undefined;
  },
): Promise<Response> {
  void options.prerenderStore;
  const response = await renderRouteModule(request, context);

  return response;
}
