export interface ReactFlowCoverageRow {
  obligationId: string;
  feature: string;
  risk: string;
  fixtureId: string;
  vrt: boolean;
  domSummary: boolean;
  interaction: boolean;
  status: "covered" | "partial" | "debt";
}

export const reactFlowCoverageLedger: ReactFlowCoverageRow[] = [
  {
    obligationId: "RF-CANVAS-001",
    feature: "ReactFlow + Background + Controls + MiniMap + Panel",
    risk: "Nodes, edges, Background, Controls, MiniMap, and Panel must mount under ReactFlow context",
    fixtureId: "react-flow-basic-canvas",
    vrt: true,
    domSummary: true,
    interaction: false,
    status: "covered",
  },
  {
    obligationId: "RF-EDGE-001",
    feature: "ReactFlow SVG edge layer",
    risk: "SVG edge paths and marker definitions must render inside the flow viewport",
    fixtureId: "react-flow-basic-canvas",
    vrt: true,
    domSummary: true,
    interaction: false,
    status: "covered",
  },
  {
    obligationId: "RF-MEASURE-001",
    feature: "Viewport measurement and transform",
    risk: "React Flow measurement and viewport transforms must stabilize in a fixed-size container",
    fixtureId: "react-flow-basic-canvas",
    vrt: true,
    domSummary: true,
    interaction: false,
    status: "covered",
  },
  {
    obligationId: "RF-HANDLE-001",
    feature: "Custom node with Handle and Position",
    risk: "Custom node components must receive data and render source and target handles",
    fixtureId: "react-flow-custom-node-handles",
    vrt: true,
    domSummary: true,
    interaction: false,
    status: "covered",
  },
  {
    obligationId: "RF-CONTROLLED-001",
    feature: "useNodesState and useEdgesState",
    risk: "Controlled node and edge state must update after pointer interaction",
    fixtureId: "react-flow-controlled-interaction",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RF-CONTROLS-001",
    feature: "Controls fitView",
    risk: "fitView control interaction must update viewport state without unmounting nodes",
    fixtureId: "react-flow-controlled-interaction",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RF-DRAG-001",
    feature: "Node drag with controlled node state",
    risk: "Dragging a node must emit controlled node position changes and preserve edge rendering",
    fixtureId: "react-flow-node-drag-position",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RF-CONNECT-001",
    feature: "connectOnClick + addEdge",
    risk: "Click-based handle connection must call onConnect and add a controlled edge",
    fixtureId: "react-flow-connect-on-click",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RF-RECONNECT-001",
    feature: "reconnectEdge + controlled edge target",
    risk: "Controlled edge reconnection must update the edge target and rerender the edge path",
    fixtureId: "react-flow-controlled-reconnect",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RF-RESIZE-001",
    feature: "NodeResizer dimensions",
    risk: "NodeResizer must render resize handles and commit dimension changes",
    fixtureId: "react-flow-node-resizer",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RF-KEYBOARD-001",
    feature: "Keyboard deletion and onNodesDelete",
    risk: "Keyboard deletion must remove selected nodes and call delete callbacks without stale selection state",
    fixtureId: "react-flow-keyboard-delete",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RF-VIEWPORT-001",
    feature: "useReactFlow and useViewport updates",
    risk: "React Flow viewport hooks must expose programmatic viewport updates through the compat store path",
    fixtureId: "react-flow-viewport-hooks",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RF-CUSTOM-EDGE-001",
    feature: "Custom edge with EdgeLabelRenderer and marker",
    risk: "Custom edge components must render marker definitions and portal-backed edge labels",
    fixtureId: "react-flow-custom-edge-labels",
    vrt: true,
    domSummary: true,
    interaction: false,
    status: "covered",
  },
  {
    obligationId: "RF-NODES-INIT-001",
    feature: "useNodesInitialized measurement state",
    risk: "useNodesInitialized must report measured node state after the viewport stabilizes",
    fixtureId: "react-flow-nodes-initialized",
    vrt: true,
    domSummary: true,
    interaction: false,
    status: "covered",
  },
  {
    obligationId: "RF-SELECTION-001",
    feature: "Selection box and onSelectionChange",
    risk: "Selection box interaction must update selected nodes and emit onSelectionChange",
    fixtureId: "react-flow-selection-box",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RF-EDGE-DELETE-001",
    feature: "Edge keyboard deletion and onEdgesDelete",
    risk: "Keyboard deletion must remove selected edges and call edge delete callbacks",
    fixtureId: "react-flow-edge-keyboard-delete",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RF-TOOLBAR-001",
    feature: "NodeToolbar and EdgeToolbar portal controls",
    risk: "NodeToolbar and EdgeToolbar portal controls must render and dispatch user actions",
    fixtureId: "react-flow-node-edge-toolbar",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RF-PARENT-CHILD-001",
    feature: "Parent child nodes with constrained extent",
    risk: "Parent child nodes must mount with constrained extent and preserve relative positioning",
    fixtureId: "react-flow-parent-child-extent",
    vrt: true,
    domSummary: true,
    interaction: false,
    status: "covered",
  },
];
