export interface RadixCoverageRow {
  obligationId: string;
  feature: string;
  risk: string;
  fixtureId: string;
  vrt: boolean;
  domSummary: boolean;
  interaction: boolean;
  status: "covered" | "partial" | "debt";
}

export const radixCoverageLedger: RadixCoverageRow[] = [
  {
    obligationId: "RADIX-ACCORDION-001",
    feature: "Accordion",
    risk: "Accordion trigger state and item content must render after delegated click interaction",
    fixtureId: "radix-accordion-opens-item",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-ALERT-DIALOG-001",
    feature: "AlertDialog",
    risk: "AlertDialog portaled modal content must mount after trigger activation",
    fixtureId: "radix-alert-dialog-opens",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-ASPECT-RATIO-001",
    feature: "AspectRatio",
    risk: "AspectRatio layout wrapper must produce stable deterministic content",
    fixtureId: "radix-aspect-ratio-renders",
    vrt: true,
    domSummary: true,
    interaction: false,
    status: "covered",
  },
  {
    obligationId: "RADIX-AVATAR-001",
    feature: "Avatar",
    risk: "Avatar fallback timing must render deterministic fallback content",
    fixtureId: "radix-avatar-renders-fallback",
    vrt: true,
    domSummary: true,
    interaction: false,
    status: "covered",
  },
  {
    obligationId: "RADIX-CHECKBOX-001",
    feature: "Checkbox",
    risk: "Checkbox checked state and indicator must update from delegated click events",
    fixtureId: "radix-checkbox-toggles",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-COLLAPSIBLE-001",
    feature: "Collapsible",
    risk: "Collapsible content must mount after trigger activation",
    fixtureId: "radix-collapsible-opens",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-CONTEXT-MENU-001",
    feature: "ContextMenu",
    risk: "ContextMenu must open from right-click pointer button metadata",
    fixtureId: "radix-context-menu-opens",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-DIALOG-001",
    feature: "Dialog.Portal",
    risk: "Portal content must mount in document.body after an interaction",
    fixtureId: "radix-dialog-opens-from-trigger",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-DIALOG-002",
    feature: "Dialog.Trigger",
    risk: "Dialog trigger and content ARIA state must match React",
    fixtureId: "radix-dialog-opens-from-trigger",
    vrt: false,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-DIALOG-003",
    feature: "Dialog.FocusScope",
    risk: "Focus must move into the dialog and return to the trigger",
    fixtureId: "radix-dialog-closes-from-open-state",
    vrt: false,
    domSummary: true,
    interaction: true,
    status: "partial",
  },
  {
    obligationId: "RADIX-DIALOG-004",
    feature: "Dialog.Close",
    risk: "Close controls must unmount portaled content",
    fixtureId: "radix-dialog-closes-from-open-state",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-DIALOG-005",
    feature: "Dialog.Escape",
    risk: "Escape must close modal dialog content",
    fixtureId: "radix-dialog-closes-with-escape",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-DIALOG-006",
    feature: "Dialog.DismissableLayer",
    risk: "Outside pointer interaction must close dismissible dialog content",
    fixtureId: "radix-dialog-closes-on-outside-click",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-POPOVER-001",
    feature: "Popover.Trigger",
    risk: "Popover trigger must mount content and expose expanded state",
    fixtureId: "radix-popover-opens-from-trigger",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-POPOVER-002",
    feature: "Popover.DismissableLayer",
    risk: "Outside pointer interaction must close dismissible popover content",
    fixtureId: "radix-popover-closes-on-outside-click",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-FORM-001",
    feature: "Form",
    risk: "Form primitives must submit through delegated submit events and update local state",
    fixtureId: "radix-form-submits",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-HOVER-CARD-001",
    feature: "HoverCard",
    risk: "HoverCard content must mount from pointer hover intent",
    fixtureId: "radix-hover-card-shows-on-hover",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-LABEL-001",
    feature: "Label",
    risk: "Label must render a linked native control without changing deterministic DOM",
    fixtureId: "radix-label-links-control",
    vrt: true,
    domSummary: true,
    interaction: false,
    status: "covered",
  },
  {
    obligationId: "RADIX-MENUBAR-001",
    feature: "Menubar",
    risk: "Menubar content must mount after menu trigger activation",
    fixtureId: "radix-menubar-opens-menu",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-NAVIGATION-MENU-001",
    feature: "NavigationMenu",
    risk: "NavigationMenu content must mount from pointer hover interaction",
    fixtureId: "radix-navigation-menu-opens-item",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-OTP-001",
    feature: "OneTimePasswordField",
    risk: "OneTimePasswordField inputs must accept typed input and keep hidden field wiring stable",
    fixtureId: "radix-one-time-password-field-accepts-input",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-PASSWORD-TOGGLE-001",
    feature: "PasswordToggleField",
    risk: "PasswordToggleField toggle must switch visibility slot text through delegated click events",
    fixtureId: "radix-password-toggle-field-toggles",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-PROGRESS-001",
    feature: "Progress",
    risk: "Progress value and indicator must render deterministic ARIA state",
    fixtureId: "radix-progress-renders-value",
    vrt: true,
    domSummary: true,
    interaction: false,
    status: "covered",
  },
  {
    obligationId: "RADIX-RADIO-GROUP-001",
    feature: "RadioGroup",
    risk: "RadioGroup selection must move to a second item through delegated click events",
    fixtureId: "radix-radio-group-selects-option",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-SCROLL-AREA-001",
    feature: "ScrollArea",
    risk: "ScrollArea viewport and scrollbar structure must render deterministically",
    fixtureId: "radix-scroll-area-renders-viewport",
    vrt: true,
    domSummary: true,
    interaction: false,
    status: "covered",
  },
  {
    obligationId: "RADIX-SELECT-001",
    feature: "Select",
    risk: "Select content must open and choose an item through portal and focus-managed interactions",
    fixtureId: "radix-select-chooses-option",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-SEPARATOR-001",
    feature: "Separator",
    risk: "Separator must render deterministic semantic divider content",
    fixtureId: "radix-separator-renders",
    vrt: true,
    domSummary: true,
    interaction: false,
    status: "covered",
  },
  {
    obligationId: "RADIX-SLIDER-001",
    feature: "Slider",
    risk: "Slider thumb must respond to keyboard events and keep ARIA state stable",
    fixtureId: "radix-slider-changes-value",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-SWITCH-001",
    feature: "Switch",
    risk: "Switch checked state must update from delegated click events",
    fixtureId: "radix-switch-toggles",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-TABS-001",
    feature: "Tabs",
    risk: "Tabs active panel must switch through trigger activation",
    fixtureId: "radix-tabs-switches-tab",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-TOAST-001",
    feature: "Toast",
    risk: "Toast content must mount after trigger activation and render in its viewport",
    fixtureId: "radix-toast-opens",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-TOGGLE-001",
    feature: "Toggle",
    risk: "Toggle pressed state must update from delegated click events",
    fixtureId: "radix-toggle-toggles",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-TOGGLE-GROUP-001",
    feature: "ToggleGroup",
    risk: "ToggleGroup selection must update from item activation",
    fixtureId: "radix-toggle-group-selects-item",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-TOOLBAR-001",
    feature: "Toolbar",
    risk: "Toolbar button and toggle primitives must handle activation inside toolbar roles",
    fixtureId: "radix-toolbar-activates-button",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-DROPDOWN-001",
    feature: "DropdownMenu.Trigger",
    risk: "DropdownMenu trigger must mount menu content and close on Escape",
    fixtureId: "radix-dropdown-menu-closes-with-escape",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-TOOLTIP-001",
    feature: "Tooltip.Trigger",
    risk: "Tooltip must mount tooltip content from hover and focus interest",
    fixtureId: "radix-tooltip-shows-on-hover",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
  {
    obligationId: "RADIX-TOOLTIP-002",
    feature: "Tooltip.Focus",
    risk: "Tooltip must mount tooltip content from hover and focus interest",
    fixtureId: "radix-tooltip-shows-on-focus",
    vrt: true,
    domSummary: true,
    interaction: true,
    status: "covered",
  },
];
